version: '2'
services:
    labfinal:
        container_name: labfinal
        image: eaanaba/labfinal:0.0.1-SNAPSHOT
        # build:
        #     context: .
        ports:
            - 8888:8080
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge